"""initial migration - fec schema

Revision ID: 2b667d303573
Revises: 
Create Date: 2025-12-11 20:12:07.358332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b667d303573'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('candidate_status', sa.Text(), nullable=True),
    sa.Column('candidate_status_full', sa.Text(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('district_number', sa.Integer(), nullable=True),
    sa.Column('election_years', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('federal_funds_flag', sa.Boolean(), nullable=True),
    sa.Column('first_file_date', sa.Date(), nullable=True),
    sa.Column('incumbent_challenge', sa.Text(), nullable=True),
    sa.Column('incumbent_challenge_full', sa.Text(), nullable=True),
    sa.Column('last_file_date', sa.Date(), nullable=True),
    sa.Column('load_date', sa.Date(), nullable=True),
    sa.Column('office', sa.Text(), nullable=True),
    sa.Column('office_full', sa.Text(), nullable=True),
    sa.Column('office_sought', sa.Text(), nullable=True),
    sa.Column('party', sa.Text(), nullable=True),
    sa.Column('party_full', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('state_full', sa.Text(), nullable=True),
    sa.Column('active_through', sa.Integer(), nullable=True),
    sa.Column('candidate_inactive', sa.Boolean(), nullable=True),
    sa.Column('candidate_election_years', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_raised_funds', sa.Boolean(), nullable=True),
    sa.Column('principal_campaign_committee_id', sa.Text(), nullable=True),
    sa.Column('principal_campaign_committee_name', sa.Text(), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('idx_candidates_candidate_id', 'candidates', ['candidate_id'], unique=False)
    op.create_index('idx_candidates_committee_ids', 'candidates', ['committee_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_candidates_cycle', 'candidates', ['cycle'], unique=False)
    op.create_index('idx_candidates_election_years', 'candidates', ['election_years'], unique=False, postgresql_using='gin')
    op.create_index('idx_candidates_name', 'candidates', ['name'], unique=False)
    op.create_index('idx_candidates_office', 'candidates', ['office'], unique=False)
    op.create_index('idx_candidates_party', 'candidates', ['party'], unique=False)
    op.create_index('idx_candidates_state', 'candidates', ['state'], unique=False)
    op.create_table('committees',
    sa.Column('committee_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('designation_full', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.Text(), nullable=True),
    sa.Column('committee_type_full', sa.Text(), nullable=True),
    sa.Column('organization_type', sa.Text(), nullable=True),
    sa.Column('organization_type_full', sa.Text(), nullable=True),
    sa.Column('party', sa.Text(), nullable=True),
    sa.Column('party_full', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('state_full', sa.Text(), nullable=True),
    sa.Column('treasurer_name', sa.Text(), nullable=True),
    sa.Column('street_1', sa.Text(), nullable=True),
    sa.Column('street_2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycles_has_activity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycles_has_financial', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_f1_date', sa.Date(), nullable=True),
    sa.Column('first_file_date', sa.Date(), nullable=True),
    sa.Column('last_f1_date', sa.Date(), nullable=True),
    sa.Column('last_file_date', sa.Date(), nullable=True),
    sa.Column('filing_frequency', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('jfc_committee', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_cycle_has_activity', sa.Integer(), nullable=True),
    sa.Column('last_cycle_has_financial', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.Text(), nullable=True),
    sa.Column('party_type_full', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sponsor_candidate_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sponsor_candidate_name', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_office', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_office_district', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_office_state', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_party', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_party_full', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_state', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_state_full', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_type', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_type_full', sa.Text(), nullable=True),
    sa.Column('sponsor_candidate_zip', sa.Text(), nullable=True),
    sa.Column('sponsor_committee_id', sa.Text(), nullable=True),
    sa.Column('sponsor_committee_name', sa.Text(), nullable=True),
    sa.Column('sponsor_committee_type', sa.Text(), nullable=True),
    sa.Column('sponsor_committee_type_full', sa.Text(), nullable=True),
    sa.Column('sponsor_committee_zip', sa.Text(), nullable=True),
    sa.Column('sponsor_name', sa.Text(), nullable=True),
    sa.Column('sponsor_state', sa.Text(), nullable=True),
    sa.Column('sponsor_state_full', sa.Text(), nullable=True),
    sa.Column('sponsor_type', sa.Text(), nullable=True),
    sa.Column('sponsor_type_full', sa.Text(), nullable=True),
    sa.Column('sponsor_zip', sa.Text(), nullable=True),
    sa.Column('terminated', sa.Boolean(), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('committee_id')
    )
    op.create_index('idx_committees_candidate_ids', 'committees', ['candidate_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_committees_committee_id', 'committees', ['committee_id'], unique=False)
    op.create_index('idx_committees_committee_type', 'committees', ['committee_type'], unique=False)
    op.create_index('idx_committees_cycles', 'committees', ['cycles'], unique=False, postgresql_using='gin')
    op.create_index('idx_committees_is_active', 'committees', ['is_active'], unique=False)
    op.create_index('idx_committees_name', 'committees', ['name'], unique=False)
    op.create_index('idx_committees_party', 'committees', ['party'], unique=False)
    op.create_index('idx_committees_state', 'committees', ['state'], unique=False)
    op.create_index('idx_committees_terminated', 'committees', ['terminated'], unique=False)
    op.create_table('purpose_keywords',
    sa.Column('kw', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kw')
    )
    op.create_table('schedule_a_contributions',
    sa.Column('amendment_indicator', sa.String(length=1), nullable=True),
    sa.Column('amendment_indicator_desc', sa.Text(), nullable=True),
    sa.Column('back_reference_schedule_name', sa.Text(), nullable=True),
    sa.Column('back_reference_transaction_id', sa.Text(), nullable=True),
    sa.Column('candidate_first_name', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.String(length=9), nullable=True),
    sa.Column('candidate_last_name', sa.Text(), nullable=True),
    sa.Column('candidate_middle_name', sa.Text(), nullable=True),
    sa.Column('candidate_name', sa.Text(), nullable=True),
    sa.Column('candidate_office', sa.String(length=1), nullable=True),
    sa.Column('candidate_office_district', sa.String(length=2), nullable=True),
    sa.Column('candidate_office_full', sa.Text(), nullable=True),
    sa.Column('candidate_office_state', sa.String(length=2), nullable=True),
    sa.Column('candidate_office_state_full', sa.Text(), nullable=True),
    sa.Column('candidate_prefix', sa.Text(), nullable=True),
    sa.Column('candidate_suffix', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.String(length=9), nullable=True),
    sa.Column('committee_name', sa.Text(), nullable=True),
    sa.Column('conduit_committee_city', sa.Text(), nullable=True),
    sa.Column('conduit_committee_id', sa.String(length=9), nullable=True),
    sa.Column('conduit_committee_name', sa.Text(), nullable=True),
    sa.Column('conduit_committee_state', sa.String(length=2), nullable=True),
    sa.Column('conduit_committee_street1', sa.Text(), nullable=True),
    sa.Column('conduit_committee_street2', sa.Text(), nullable=True),
    sa.Column('conduit_committee_zip', sa.String(length=10), nullable=True),
    sa.Column('contribution_receipt_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contribution_receipt_date', sa.Date(), nullable=True),
    sa.Column('contributor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributor_aggregate_ytd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contributor_city', sa.Text(), nullable=True),
    sa.Column('contributor_employer', sa.Text(), nullable=True),
    sa.Column('contributor_first_name', sa.Text(), nullable=True),
    sa.Column('contributor_id', sa.String(length=9), nullable=True),
    sa.Column('contributor_last_name', sa.Text(), nullable=True),
    sa.Column('contributor_middle_name', sa.Text(), nullable=True),
    sa.Column('contributor_name', sa.Text(), nullable=True),
    sa.Column('contributor_occupation', sa.Text(), nullable=True),
    sa.Column('contributor_prefix', sa.Text(), nullable=True),
    sa.Column('contributor_state', sa.String(length=2), nullable=True),
    sa.Column('contributor_street_1', sa.Text(), nullable=True),
    sa.Column('contributor_street_2', sa.Text(), nullable=True),
    sa.Column('contributor_suffix', sa.Text(), nullable=True),
    sa.Column('contributor_zip', sa.String(length=10), nullable=True),
    sa.Column('donor_committee_name', sa.Text(), nullable=True),
    sa.Column('election_type', sa.String(length=5), nullable=True),
    sa.Column('election_type_full', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=3), nullable=True),
    sa.Column('entity_type_desc', sa.Text(), nullable=True),
    sa.Column('fec_election_type_desc', sa.Text(), nullable=True),
    sa.Column('fec_election_year', sa.Integer(), nullable=True),
    sa.Column('file_number', sa.Integer(), nullable=True),
    sa.Column('filing_form', sa.String(length=8), nullable=True),
    sa.Column('image_number', sa.BigInteger(), nullable=True),
    sa.Column('increased_limit', sa.Boolean(), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.String(length=8), nullable=True),
    sa.Column('line_number_label', sa.Text(), nullable=True),
    sa.Column('link_id', sa.BigInteger(), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.Column('memo_code', sa.String(length=1), nullable=True),
    sa.Column('memo_code_full', sa.Text(), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('memoed_subtotal', sa.Boolean(), nullable=True),
    sa.Column('national_committee_nonfederal_account', sa.Text(), nullable=True),
    sa.Column('original_sub_id', sa.BigInteger(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('receipt_type', sa.String(length=3), nullable=True),
    sa.Column('receipt_type_desc', sa.Text(), nullable=True),
    sa.Column('receipt_type_full', sa.Text(), nullable=True),
    sa.Column('recipient_committee_designation', sa.String(length=3), nullable=True),
    sa.Column('recipient_committee_org_type', sa.String(length=3), nullable=True),
    sa.Column('recipient_committee_type', sa.String(length=3), nullable=True),
    sa.Column('report_type', sa.String(length=8), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(length=8), nullable=True),
    sa.Column('schedule_type_full', sa.Text(), nullable=True),
    sa.Column('sub_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('two_year_transaction_period', sa.Integer(), nullable=True),
    sa.Column('unused_contbr_id', sa.String(length=9), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index('idx_schedule_a_amount', 'schedule_a_contributions', ['contribution_receipt_amount'], unique=False)
    op.create_index('idx_schedule_a_committee_id', 'schedule_a_contributions', ['committee_id'], unique=False)
    op.create_index('idx_schedule_a_date', 'schedule_a_contributions', ['contribution_receipt_date'], unique=False)
    op.create_index('idx_schedule_a_two_year_period', 'schedule_a_contributions', ['two_year_transaction_period'], unique=False)
    op.create_table('schedule_b_disbursements',
    sa.Column('amendment_indicator', sa.Text(), nullable=True),
    sa.Column('amendment_indicator_desc', sa.Text(), nullable=True),
    sa.Column('back_reference_schedule_name', sa.Text(), nullable=True),
    sa.Column('back_reference_transaction_id', sa.Text(), nullable=True),
    sa.Column('beneficiary_committee_name', sa.Text(), nullable=True),
    sa.Column('candidate_first_name', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.Text(), nullable=True),
    sa.Column('candidate_last_name', sa.Text(), nullable=True),
    sa.Column('candidate_middle_name', sa.Text(), nullable=True),
    sa.Column('candidate_name', sa.Text(), nullable=True),
    sa.Column('candidate_office', sa.Text(), nullable=True),
    sa.Column('candidate_office_district', sa.Text(), nullable=True),
    sa.Column('candidate_office_full', sa.Text(), nullable=True),
    sa.Column('candidate_office_state', sa.Text(), nullable=True),
    sa.Column('candidate_office_state_full', sa.Text(), nullable=True),
    sa.Column('candidate_party', sa.Text(), nullable=True),
    sa.Column('candidate_prefix', sa.Text(), nullable=True),
    sa.Column('candidate_suffix', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.Text(), nullable=True),
    sa.Column('committee_name', sa.Text(), nullable=True),
    sa.Column('conduit_committee_city', sa.Text(), nullable=True),
    sa.Column('conduit_committee_id', sa.Text(), nullable=True),
    sa.Column('conduit_committee_name', sa.Text(), nullable=True),
    sa.Column('conduit_committee_state', sa.Text(), nullable=True),
    sa.Column('conduit_committee_street1', sa.Text(), nullable=True),
    sa.Column('conduit_committee_street2', sa.Text(), nullable=True),
    sa.Column('conduit_committee_zip', sa.Text(), nullable=True),
    sa.Column('disbursement_amount', sa.Numeric(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('disbursement_description', sa.Text(), nullable=True),
    sa.Column('disbursement_type', sa.Text(), nullable=True),
    sa.Column('disbursement_type_full', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_type_desc', sa.Text(), nullable=True),
    sa.Column('fec_election_type_desc', sa.Text(), nullable=True),
    sa.Column('fec_election_year', sa.Integer(), nullable=True),
    sa.Column('file_number', sa.Integer(), nullable=True),
    sa.Column('filing_form', sa.Text(), nullable=True),
    sa.Column('image_number', sa.Text(), nullable=True),
    sa.Column('is_electioneering_communication', sa.Boolean(), nullable=True),
    sa.Column('is_independent_expenditure', sa.Boolean(), nullable=True),
    sa.Column('is_party_expenditure', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.Text(), nullable=True),
    sa.Column('line_number_label', sa.Text(), nullable=True),
    sa.Column('link_id', sa.BigInteger(), nullable=True),
    sa.Column('load_date', sa.Date(), nullable=True),
    sa.Column('memo_code', sa.Text(), nullable=True),
    sa.Column('memo_code_full', sa.Text(), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('memoed_subtotal', sa.Boolean(), nullable=True),
    sa.Column('national_committee_nonfederal_account', sa.Text(), nullable=True),
    sa.Column('original_sub_id', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('recipient_city', sa.Text(), nullable=True),
    sa.Column('recipient_committee_designation', sa.Text(), nullable=True),
    sa.Column('recipient_committee_designation_full', sa.Text(), nullable=True),
    sa.Column('recipient_committee_id', sa.Text(), nullable=True),
    sa.Column('recipient_committee_name', sa.Text(), nullable=True),
    sa.Column('recipient_committee_org_type', sa.Text(), nullable=True),
    sa.Column('recipient_committee_org_type_full', sa.Text(), nullable=True),
    sa.Column('recipient_committee_type', sa.Text(), nullable=True),
    sa.Column('recipient_committee_type_full', sa.Text(), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('recipient_state', sa.Text(), nullable=True),
    sa.Column('recipient_street_1', sa.Text(), nullable=True),
    sa.Column('recipient_street_2', sa.Text(), nullable=True),
    sa.Column('recipient_zip', sa.Text(), nullable=True),
    sa.Column('ref_disp_excess_amt', sa.Numeric(), nullable=True),
    sa.Column('ref_disp_excess_amt_desc', sa.Text(), nullable=True),
    sa.Column('ref_disp_excess_flg', sa.Text(), nullable=True),
    sa.Column('ref_disp_excess_flg_desc', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Text(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Text(), nullable=True),
    sa.Column('schedule_type_full', sa.Text(), nullable=True),
    sa.Column('semi_annual_bundled_refund', sa.Numeric(), nullable=True),
    sa.Column('sub_id', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('two_year_transaction_period', sa.Integer(), nullable=True),
    sa.Column('unused_recipient_id', sa.Text(), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index('idx_sched_b_candidate_id', 'schedule_b_disbursements', ['candidate_id'], unique=False)
    op.create_index('idx_sched_b_committee_id', 'schedule_b_disbursements', ['committee_id'], unique=False)
    op.create_index('idx_sched_b_disb_date', 'schedule_b_disbursements', ['disbursement_date'], unique=False)
    op.create_index('idx_sched_b_recipient_name', 'schedule_b_disbursements', ['recipient_name'], unique=False)
    op.create_index('idx_sched_b_report_year', 'schedule_b_disbursements', ['report_year'], unique=False)
    op.create_index('idx_sched_b_transaction_id', 'schedule_b_disbursements', ['transaction_id'], unique=False)
    op.create_index('idx_schedb_disbursement_description_trgm', 'schedule_b_disbursements', ['disbursement_description'], unique=False, postgresql_using='gin', postgresql_ops={'disbursement_description': 'gin_trgm_ops'})
    op.create_index('idx_schedb_recipient_trgm', 'schedule_b_disbursements', ['recipient_name'], unique=False, postgresql_using='gin', postgresql_ops={'recipient_name': 'gin_trgm_ops'})
    op.create_table('schedule_e_expenditures',
    sa.Column('action_code', sa.Text(), nullable=True),
    sa.Column('action_code_full', sa.Text(), nullable=True),
    sa.Column('amendment_indicator', sa.Text(), nullable=True),
    sa.Column('amendment_number', sa.Integer(), nullable=True),
    sa.Column('amendment_indicator_desc', sa.Text(), nullable=True),
    sa.Column('back_reference_schedule_name', sa.Text(), nullable=True),
    sa.Column('back_reference_transaction_id', sa.Text(), nullable=True),
    sa.Column('candidate', sa.Text(), nullable=True),
    sa.Column('candidate_first_name', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.Text(), nullable=True),
    sa.Column('candidate_last_name', sa.Text(), nullable=True),
    sa.Column('candidate_middle_name', sa.Text(), nullable=True),
    sa.Column('candidate_name', sa.Text(), nullable=True),
    sa.Column('candidate_office', sa.Text(), nullable=True),
    sa.Column('candidate_office_district', sa.Text(), nullable=True),
    sa.Column('candidate_office_full', sa.Text(), nullable=True),
    sa.Column('candidate_office_state', sa.Text(), nullable=True),
    sa.Column('candidate_office_state_full', sa.Text(), nullable=True),
    sa.Column('candidate_party', sa.Text(), nullable=True),
    sa.Column('candidate_prefix', sa.Text(), nullable=True),
    sa.Column('candidate_suffix', sa.Text(), nullable=True),
    sa.Column('affiliated_committee_name', sa.Text(), nullable=True),
    sa.Column('candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_city', sa.Text(), nullable=True),
    sa.Column('committee_committee_id', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.Text(), nullable=True),
    sa.Column('committee_type_full', sa.Text(), nullable=True),
    sa.Column('committee_cycle', sa.Integer(), nullable=True),
    sa.Column('committee_cycles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_cycles_has_activity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_cycles_has_financial', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_designation', sa.Text(), nullable=True),
    sa.Column('committee_designation_full', sa.Text(), nullable=True),
    sa.Column('committee_filing_frequency', sa.Text(), nullable=True),
    sa.Column('committee_first_f1_date', sa.Date(), nullable=True),
    sa.Column('committee_first_file_date', sa.Date(), nullable=True),
    sa.Column('committee_is_active', sa.Boolean(), nullable=True),
    sa.Column('committee_jfc_committee', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committee_last_cycle_has_activity', sa.Integer(), nullable=True),
    sa.Column('committee_last_cycle_has_financial', sa.Integer(), nullable=True),
    sa.Column('committee_last_f1_date', sa.Date(), nullable=True),
    sa.Column('committee_last_file_date', sa.Date(), nullable=True),
    sa.Column('committee_name', sa.Text(), nullable=True),
    sa.Column('committee_organization_type', sa.Text(), nullable=True),
    sa.Column('committee_organization_type_full', sa.Text(), nullable=True),
    sa.Column('committee_party', sa.Text(), nullable=True),
    sa.Column('committee_party_full', sa.Text(), nullable=True),
    sa.Column('committee_state', sa.Text(), nullable=True),
    sa.Column('committee_state_full', sa.Text(), nullable=True),
    sa.Column('committee_street_1', sa.Text(), nullable=True),
    sa.Column('committee_street_2', sa.Text(), nullable=True),
    sa.Column('committee_treasurer_name', sa.Text(), nullable=True),
    sa.Column('committee_zip', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.Text(), nullable=True),
    sa.Column('committee_name2', sa.Text(), nullable=True),
    sa.Column('conduit_committee_city', sa.Text(), nullable=True),
    sa.Column('conduit_committee_id', sa.Text(), nullable=True),
    sa.Column('conduit_committee_name', sa.Text(), nullable=True),
    sa.Column('conduit_committee_state', sa.Text(), nullable=True),
    sa.Column('conduit_committee_street1', sa.Text(), nullable=True),
    sa.Column('conduit_committee_street2', sa.Text(), nullable=True),
    sa.Column('conduit_committee_zip', sa.Text(), nullable=True),
    sa.Column('disbursement_dt', sa.Date(), nullable=True),
    sa.Column('dissemination_date', sa.Date(), nullable=True),
    sa.Column('election_type', sa.Text(), nullable=True),
    sa.Column('election_type_full', sa.Text(), nullable=True),
    sa.Column('expenditure_amount', sa.Numeric(), nullable=True),
    sa.Column('expenditure_date', sa.Date(), nullable=True),
    sa.Column('expenditure_description', sa.Text(), nullable=True),
    sa.Column('file_number', sa.Integer(), nullable=True),
    sa.Column('filer_first_name', sa.Text(), nullable=True),
    sa.Column('filer_last_name', sa.Text(), nullable=True),
    sa.Column('filer_middle_name', sa.Text(), nullable=True),
    sa.Column('filer_prefix', sa.Text(), nullable=True),
    sa.Column('filer_suffix', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_form', sa.Text(), nullable=True),
    sa.Column('form_line_number', sa.Text(), nullable=True),
    sa.Column('image_number', sa.Text(), nullable=True),
    sa.Column('independent_sign_date', sa.Date(), nullable=True),
    sa.Column('independent_sign_name', sa.Text(), nullable=True),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.Text(), nullable=True),
    sa.Column('line_number_label', sa.Text(), nullable=True),
    sa.Column('link_id', sa.BigInteger(), nullable=True),
    sa.Column('memo_code', sa.Text(), nullable=True),
    sa.Column('memo_code_full', sa.Text(), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('memoed_subtotal', sa.Boolean(), nullable=True),
    sa.Column('most_recent', sa.Boolean(), nullable=True),
    sa.Column('notary_commission_expiration_date', sa.Date(), nullable=True),
    sa.Column('notary_sign_date', sa.Date(), nullable=True),
    sa.Column('notary_sign_name', sa.Text(), nullable=True),
    sa.Column('office_total_ytd', sa.Numeric(), nullable=True),
    sa.Column('original_sub_id', sa.Text(), nullable=True),
    sa.Column('payee_city', sa.Text(), nullable=True),
    sa.Column('payee_first_name', sa.Text(), nullable=True),
    sa.Column('payee_last_name', sa.Text(), nullable=True),
    sa.Column('payee_middle_name', sa.Text(), nullable=True),
    sa.Column('payee_name', sa.Text(), nullable=True),
    sa.Column('payee_prefix', sa.Text(), nullable=True),
    sa.Column('payee_state', sa.Text(), nullable=True),
    sa.Column('payee_street_1', sa.Text(), nullable=True),
    sa.Column('payee_street_2', sa.Text(), nullable=True),
    sa.Column('payee_suffix', sa.Text(), nullable=True),
    sa.Column('payee_zip', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('previous_file_number', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Text(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Text(), nullable=True),
    sa.Column('schedule_type_full', sa.Text(), nullable=True),
    sa.Column('semi_annual_bundled_refund', sa.Boolean(), nullable=True),
    sa.Column('sub_id', sa.Text(), nullable=False),
    sa.Column('support_oppose_indicator', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index('idx_schedule_e_candidate_id', 'schedule_e_expenditures', ['candidate_id'], unique=False)
    op.create_index('idx_schedule_e_committee_id', 'schedule_e_expenditures', ['committee_id'], unique=False)
    op.create_index('idx_schedule_e_expenditure_date', 'schedule_e_expenditures', ['expenditure_date'], unique=False)
    op.create_index('idx_schedule_e_filing_date', 'schedule_e_expenditures', ['filing_date'], unique=False)
    op.create_index('idx_schedule_e_report_year', 'schedule_e_expenditures', ['report_year'], unique=False)
    op.create_table('vendor_category_manual',
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('recipient_name')
    )
    op.create_table('vendor_name_keywords',
    sa.Column('kw', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kw')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_name_keywords')
    op.drop_table('vendor_category_manual')
    op.drop_index('idx_schedule_e_report_year', table_name='schedule_e_expenditures')
    op.drop_index('idx_schedule_e_filing_date', table_name='schedule_e_expenditures')
    op.drop_index('idx_schedule_e_expenditure_date', table_name='schedule_e_expenditures')
    op.drop_index('idx_schedule_e_committee_id', table_name='schedule_e_expenditures')
    op.drop_index('idx_schedule_e_candidate_id', table_name='schedule_e_expenditures')
    op.drop_table('schedule_e_expenditures')
    op.drop_index('idx_schedb_recipient_trgm', table_name='schedule_b_disbursements', postgresql_using='gin', postgresql_ops={'recipient_name': 'gin_trgm_ops'})
    op.drop_index('idx_schedb_disbursement_description_trgm', table_name='schedule_b_disbursements', postgresql_using='gin', postgresql_ops={'disbursement_description': 'gin_trgm_ops'})
    op.drop_index('idx_sched_b_transaction_id', table_name='schedule_b_disbursements')
    op.drop_index('idx_sched_b_report_year', table_name='schedule_b_disbursements')
    op.drop_index('idx_sched_b_recipient_name', table_name='schedule_b_disbursements')
    op.drop_index('idx_sched_b_disb_date', table_name='schedule_b_disbursements')
    op.drop_index('idx_sched_b_committee_id', table_name='schedule_b_disbursements')
    op.drop_index('idx_sched_b_candidate_id', table_name='schedule_b_disbursements')
    op.drop_table('schedule_b_disbursements')
    op.drop_index('idx_schedule_a_two_year_period', table_name='schedule_a_contributions')
    op.drop_index('idx_schedule_a_date', table_name='schedule_a_contributions')
    op.drop_index('idx_schedule_a_committee_id', table_name='schedule_a_contributions')
    op.drop_index('idx_schedule_a_amount', table_name='schedule_a_contributions')
    op.drop_table('schedule_a_contributions')
    op.drop_table('purpose_keywords')
    op.drop_index('idx_committees_terminated', table_name='committees')
    op.drop_index('idx_committees_state', table_name='committees')
    op.drop_index('idx_committees_party', table_name='committees')
    op.drop_index('idx_committees_name', table_name='committees')
    op.drop_index('idx_committees_is_active', table_name='committees')
    op.drop_index('idx_committees_cycles', table_name='committees', postgresql_using='gin')
    op.drop_index('idx_committees_committee_type', table_name='committees')
    op.drop_index('idx_committees_committee_id', table_name='committees')
    op.drop_index('idx_committees_candidate_ids', table_name='committees', postgresql_using='gin')
    op.drop_table('committees')
    op.drop_index('idx_candidates_state', table_name='candidates')
    op.drop_index('idx_candidates_party', table_name='candidates')
    op.drop_index('idx_candidates_office', table_name='candidates')
    op.drop_index('idx_candidates_name', table_name='candidates')
    op.drop_index('idx_candidates_election_years', table_name='candidates', postgresql_using='gin')
    op.drop_index('idx_candidates_cycle', table_name='candidates')
    op.drop_index('idx_candidates_committee_ids', table_name='candidates', postgresql_using='gin')
    op.drop_index('idx_candidates_candidate_id', table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
