"""remove vendor categorization tables + view (moving to reporting-pipeline)

Revision ID: 895c1a422122
Revises: 8c1f0a2b3d4e
Create Date: 2025-12-20 17:03:55.779534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '895c1a422122'
down_revision: Union[str, Sequence[str], None] = '8c1f0a2b3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS vendor_category_map;")
    op.drop_table('vendor_name_keywords')
    op.drop_table('purpose_keywords')
    op.drop_table('vendor_category_manual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vendor_name_keywords',
        sa.Column('kw', sa.Text(), nullable=False),
        sa.Column('category', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('kw'),
    )

    op.create_table(
        'purpose_keywords',
        sa.Column('kw', sa.Text(), nullable=False),
        sa.Column('category', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('kw'),
    )

    op.create_table(
        'vendor_category_manual',
        sa.Column('recipient_name', sa.Text(), nullable=False),
        sa.Column('category', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('recipient_name'),
    )

    # (Re)create the view used by reporting/analysis.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute(
        """
        CREATE OR REPLACE VIEW vendor_category_map AS
        WITH all_vendors AS (
            SELECT DISTINCT recipient_name
            FROM   schedule_b_disbursements
        ),
        name_cat AS (
            SELECT av.recipient_name,
                   MIN(vnk.category) AS name_category
            FROM   all_vendors av
            JOIN   vendor_name_keywords vnk
              ON   LOWER(av.recipient_name) LIKE '%'||vnk.kw||'%'
            GROUP  BY av.recipient_name
        ),
        purpose_cat AS (
            SELECT sb.recipient_name,
                   MIN(pk.category) AS purpose_category
            FROM   schedule_b_disbursements sb
            JOIN   purpose_keywords pk
              ON   LOWER(sb.disbursement_description) LIKE '%'||pk.kw||'%'
            GROUP  BY sb.recipient_name
        )
        SELECT
            av.recipient_name,
            COALESCE(
                vcm_manual.category,
                pc.purpose_category,
                nc.name_category,
                'Other'
            ) AS category
        FROM   all_vendors                 av
        LEFT   JOIN vendor_category_manual vcm_manual USING (recipient_name)
        LEFT   JOIN name_cat               nc          USING (recipient_name)
        LEFT   JOIN purpose_cat            pc          USING (recipient_name);
        """
    )
    # ### end Alembic commands ###
