from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

from .base import Base


class Candidate(Base):
    __tablename__ = "candidates"

    candidate_id = Column(Text, primary_key=True)
    name = Column(Text)
    candidate_status = Column(Text)
    candidate_status_full = Column(Text)
    cycle = Column(Integer)
    district = Column(Text)
    district_number = Column(Integer)
    election_years = Column(JSONB)
    federal_funds_flag = Column(Boolean)
    first_file_date = Column(Date)
    incumbent_challenge = Column(Text)
    incumbent_challenge_full = Column(Text)
    last_file_date = Column(Date)
    load_date = Column(Date)
    office = Column(Text)
    office_full = Column(Text)
    office_sought = Column(Text)
    party = Column(Text)
    party_full = Column(Text)
    state = Column(Text)
    state_full = Column(Text)
    active_through = Column(Integer)
    candidate_inactive = Column(Boolean)
    candidate_election_years = Column(JSONB)
    committee_ids = Column(JSONB)
    has_raised_funds = Column(Boolean)
    principal_campaign_committee_id = Column(Text)
    principal_campaign_committee_name = Column(Text)
    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_candidates_candidate_id", Candidate.candidate_id)
Index("idx_candidates_name", Candidate.name)
Index("idx_candidates_state", Candidate.state)
Index("idx_candidates_party", Candidate.party)
Index("idx_candidates_office", Candidate.office)
Index("idx_candidates_cycle", Candidate.cycle)
Index("idx_candidates_committee_ids", Candidate.committee_ids, postgresql_using="gin")
Index("idx_candidates_election_years", Candidate.election_years, postgresql_using="gin")


class Committee(Base):
    __tablename__ = "committees"

    committee_id = Column(Text, primary_key=True)
    name = Column(Text)
    designation = Column(Text)
    designation_full = Column(Text)
    committee_type = Column(Text)
    committee_type_full = Column(Text)
    organization_type = Column(Text)
    organization_type_full = Column(Text)
    party = Column(Text)
    party_full = Column(Text)
    state = Column(Text)
    state_full = Column(Text)
    treasurer_name = Column(Text)
    street_1 = Column(Text)
    street_2 = Column(Text)
    city = Column(Text)
    zip = Column(Text)
    candidate_ids = Column(JSONB)
    cycles = Column(JSONB)
    cycles_has_activity = Column(JSONB)
    cycles_has_financial = Column(JSONB)
    first_f1_date = Column(Date)
    first_file_date = Column(Date)
    last_f1_date = Column(Date)
    last_file_date = Column(Date)
    filing_frequency = Column(Text)
    is_active = Column(Boolean)
    jfc_committee = Column(JSONB)
    last_cycle_has_activity = Column(Integer)
    last_cycle_has_financial = Column(Integer)
    cycle = Column(Integer)
    party_type = Column(Text)
    party_type_full = Column(Text)
    sponsor_candidate_ids = Column(JSONB)
    sponsor_candidate_list = Column(JSONB)
    sponsor_candidate_name = Column(Text)
    sponsor_candidate_office = Column(Text)
    sponsor_candidate_office_district = Column(Text)
    sponsor_candidate_office_state = Column(Text)
    sponsor_candidate_party = Column(Text)
    sponsor_candidate_party_full = Column(Text)
    sponsor_candidate_state = Column(Text)
    sponsor_candidate_state_full = Column(Text)
    sponsor_candidate_type = Column(Text)
    sponsor_candidate_type_full = Column(Text)
    sponsor_candidate_zip = Column(Text)
    sponsor_committee_id = Column(Text)
    sponsor_committee_name = Column(Text)
    sponsor_committee_type = Column(Text)
    sponsor_committee_type_full = Column(Text)
    sponsor_committee_zip = Column(Text)
    sponsor_name = Column(Text)
    sponsor_state = Column(Text)
    sponsor_state_full = Column(Text)
    sponsor_type = Column(Text)
    sponsor_type_full = Column(Text)
    sponsor_zip = Column(Text)
    terminated = Column(Boolean)
    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_committees_committee_id", Committee.committee_id)
Index("idx_committees_name", Committee.name)
Index("idx_committees_state", Committee.state)
Index("idx_committees_party", Committee.party)
Index("idx_committees_committee_type", Committee.committee_type)
Index("idx_committees_cycles", Committee.cycles, postgresql_using="gin")
Index("idx_committees_candidate_ids", Committee.candidate_ids, postgresql_using="gin")
Index("idx_committees_is_active", Committee.is_active)
Index("idx_committees_terminated", Committee.terminated)


class ScheduleAContribution(Base):
    __tablename__ = "schedule_a_contributions"

    amendment_indicator = Column(String(1))
    amendment_indicator_desc = Column(Text)
    back_reference_schedule_name = Column(Text)
    back_reference_transaction_id = Column(Text)
    candidate_first_name = Column(Text)
    candidate_id = Column(String(9))
    candidate_last_name = Column(Text)
    candidate_middle_name = Column(Text)
    candidate_name = Column(Text)
    candidate_office = Column(String(1))
    candidate_office_district = Column(String(2))
    candidate_office_full = Column(Text)
    candidate_office_state = Column(String(2))
    candidate_office_state_full = Column(Text)
    candidate_prefix = Column(Text)
    candidate_suffix = Column(Text)
    committee_id = Column(String(9))
    committee_name = Column(Text)
    conduit_committee_city = Column(Text)
    conduit_committee_id = Column(String(9))
    conduit_committee_name = Column(Text)
    conduit_committee_state = Column(String(2))
    conduit_committee_street1 = Column(Text)
    conduit_committee_street2 = Column(Text)
    conduit_committee_zip = Column(String(10))
    contribution_receipt_amount = Column(Numeric(14, 2))
    contribution_receipt_date = Column(Date)
    contributor = Column(JSONB)
    contributor_aggregate_ytd = Column(Numeric(14, 2))
    contributor_city = Column(Text)
    contributor_employer = Column(Text)
    contributor_first_name = Column(Text)
    contributor_id = Column(String(9))
    contributor_last_name = Column(Text)
    contributor_middle_name = Column(Text)
    contributor_name = Column(Text)
    contributor_occupation = Column(Text)
    contributor_prefix = Column(Text)
    contributor_state = Column(String(2))
    contributor_street_1 = Column(Text)
    contributor_street_2 = Column(Text)
    contributor_suffix = Column(Text)
    contributor_zip = Column(String(10))
    donor_committee_name = Column(Text)
    election_type = Column(String(5))
    election_type_full = Column(Text)
    entity_type = Column(String(3))
    entity_type_desc = Column(Text)
    fec_election_type_desc = Column(Text)
    fec_election_year = Column(Integer)
    file_number = Column(Integer)
    filing_form = Column(String(8))
    image_number = Column(BigInteger)
    increased_limit = Column(Boolean)
    is_individual = Column(Boolean)
    line_number = Column(String(8))
    line_number_label = Column(Text)
    link_id = Column(BigInteger)
    load_date = Column(DateTime)
    memo_code = Column(String(1))
    memo_code_full = Column(Text)
    memo_text = Column(Text)
    memoed_subtotal = Column(Boolean)
    national_committee_nonfederal_account = Column(Text)
    original_sub_id = Column(BigInteger)
    pdf_url = Column(Text)
    receipt_type = Column(String(3))
    receipt_type_desc = Column(Text)
    receipt_type_full = Column(Text)
    recipient_committee_designation = Column(String(3))
    recipient_committee_org_type = Column(String(3))
    recipient_committee_type = Column(String(3))
    report_type = Column(String(8))
    report_year = Column(Integer)
    schedule_type = Column(String(8))
    schedule_type_full = Column(Text)
    sub_id = Column(BigInteger, primary_key=True)
    transaction_id = Column(String(32))
    two_year_transaction_period = Column(Integer)
    unused_contbr_id = Column(String(9))
    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_schedule_a_committee_id", ScheduleAContribution.committee_id)
Index("idx_schedule_a_two_year_period", ScheduleAContribution.two_year_transaction_period)
Index("idx_schedule_a_amount", ScheduleAContribution.contribution_receipt_amount)
Index("idx_schedule_a_date", ScheduleAContribution.contribution_receipt_date)


class ScheduleBDisbursement(Base):
    __tablename__ = "schedule_b_disbursements"

    amendment_indicator = Column(Text)
    amendment_indicator_desc = Column(Text)
    back_reference_schedule_name = Column(Text)
    back_reference_transaction_id = Column(Text)
    beneficiary_committee_name = Column(Text)
    candidate_first_name = Column(Text)
    candidate_id = Column(Text)
    candidate_last_name = Column(Text)
    candidate_middle_name = Column(Text)
    candidate_name = Column(Text)
    candidate_office = Column(Text)
    candidate_office_district = Column(Text)
    candidate_office_full = Column(Text)
    candidate_office_state = Column(Text)
    candidate_office_state_full = Column(Text)
    candidate_party = Column(Text)
    candidate_prefix = Column(Text)
    candidate_suffix = Column(Text)
    committee_id = Column(Text)
    committee_name = Column(Text)
    conduit_committee_city = Column(Text)
    conduit_committee_id = Column(Text)
    conduit_committee_name = Column(Text)
    conduit_committee_state = Column(Text)
    conduit_committee_street1 = Column(Text)
    conduit_committee_street2 = Column(Text)
    conduit_committee_zip = Column(Text)
    disbursement_amount = Column(Numeric)
    disbursement_date = Column(Date)
    disbursement_description = Column(Text)
    disbursement_type = Column(Text)
    disbursement_type_full = Column(Text)
    entity_type = Column(Text)
    entity_type_desc = Column(Text)
    fec_election_type_desc = Column(Text)
    fec_election_year = Column(Integer)
    file_number = Column(Integer)
    filing_form = Column(Text)
    image_number = Column(Text)
    is_electioneering_communication = Column(Boolean)
    is_independent_expenditure = Column(Boolean)
    is_party_expenditure = Column(Boolean)
    line_number = Column(Text)
    line_number_label = Column(Text)
    link_id = Column(BigInteger)
    load_date = Column(Date)
    memo_code = Column(Text)
    memo_code_full = Column(Text)
    memo_text = Column(Text)
    memoed_subtotal = Column(Boolean)
    national_committee_nonfederal_account = Column(Text)
    original_sub_id = Column(Text)
    pdf_url = Column(Text)
    recipient_city = Column(Text)
    recipient_committee_designation = Column(Text)
    recipient_committee_designation_full = Column(Text)
    recipient_committee_id = Column(Text)
    recipient_committee_name = Column(Text)
    recipient_committee_org_type = Column(Text)
    recipient_committee_org_type_full = Column(Text)
    recipient_committee_type = Column(Text)
    recipient_committee_type_full = Column(Text)
    recipient_name = Column(Text)
    recipient_state = Column(Text)
    recipient_street_1 = Column(Text)
    recipient_street_2 = Column(Text)
    recipient_zip = Column(Text)
    ref_disp_excess_amt = Column(Numeric)
    ref_disp_excess_amt_desc = Column(Text)
    ref_disp_excess_flg = Column(Text)
    ref_disp_excess_flg_desc = Column(Text)
    report_type = Column(Text)
    report_year = Column(Integer)
    schedule_type = Column(Text)
    schedule_type_full = Column(Text)
    semi_annual_bundled_refund = Column(Numeric)
    sub_id = Column(Text, primary_key=True)
    transaction_id = Column(Text)
    two_year_transaction_period = Column(Integer)
    unused_recipient_id = Column(Text)
    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_sched_b_disb_date", ScheduleBDisbursement.disbursement_date)
Index("idx_sched_b_committee_id", ScheduleBDisbursement.committee_id)
Index("idx_sched_b_candidate_id", ScheduleBDisbursement.candidate_id)
Index("idx_sched_b_report_year", ScheduleBDisbursement.report_year)
Index("idx_sched_b_recipient_name", ScheduleBDisbursement.recipient_name)
Index("idx_sched_b_transaction_id", ScheduleBDisbursement.transaction_id)
Index(
    "idx_schedb_recipient_trgm",
    ScheduleBDisbursement.recipient_name,
    postgresql_using="gin",
    postgresql_ops={"recipient_name": "gin_trgm_ops"},
)
Index(
    "idx_schedb_disbursement_description_trgm",
    ScheduleBDisbursement.disbursement_description,
    postgresql_using="gin",
    postgresql_ops={"disbursement_description": "gin_trgm_ops"},
)


class ScheduleEExpenditure(Base):
    __tablename__ = "schedule_e_expenditures"

    action_code = Column(Text)
    action_code_full = Column(Text)
    amendment_indicator = Column(Text)
    amendment_number = Column(Integer)
    amendment_indicator_desc = Column(Text)
    back_reference_schedule_name = Column(Text)
    back_reference_transaction_id = Column(Text)
    candidate = Column(Text)
    candidate_first_name = Column(Text)
    candidate_id = Column(Text)
    candidate_last_name = Column(Text)
    candidate_middle_name = Column(Text)
    candidate_name = Column(Text)
    candidate_office = Column(Text)
    candidate_office_district = Column(Text)
    candidate_office_full = Column(Text)
    candidate_office_state = Column(Text)
    candidate_office_state_full = Column(Text)
    candidate_party = Column(Text)
    candidate_prefix = Column(Text)
    candidate_suffix = Column(Text)

    affiliated_committee_name = Column(Text)
    candidate_ids = Column(JSONB)
    committee_city = Column(Text)
    committee_committee_id = Column(Text)
    committee_type = Column(Text)
    committee_type_full = Column(Text)
    committee_cycle = Column(Integer)
    committee_cycles = Column(JSONB)
    committee_cycles_has_activity = Column(JSONB)
    committee_cycles_has_financial = Column(JSONB)
    committee_designation = Column(Text)
    committee_designation_full = Column(Text)
    committee_filing_frequency = Column(Text)
    committee_first_f1_date = Column(Date)
    committee_first_file_date = Column(Date)
    committee_is_active = Column(Boolean)
    committee_jfc_committee = Column(JSONB)
    committee_last_cycle_has_activity = Column(Integer)
    committee_last_cycle_has_financial = Column(Integer)
    committee_last_f1_date = Column(Date)
    committee_last_file_date = Column(Date)
    committee_name = Column(Text)
    committee_organization_type = Column(Text)
    committee_organization_type_full = Column(Text)
    committee_party = Column(Text)
    committee_party_full = Column(Text)
    committee_state = Column(Text)
    committee_state_full = Column(Text)
    committee_street_1 = Column(Text)
    committee_street_2 = Column(Text)
    committee_treasurer_name = Column(Text)
    committee_zip = Column(Text)

    committee_id = Column(Text)
    committee_name2 = Column(Text)
    conduit_committee_city = Column(Text)
    conduit_committee_id = Column(Text)
    conduit_committee_name = Column(Text)
    conduit_committee_state = Column(Text)
    conduit_committee_street1 = Column(Text)
    conduit_committee_street2 = Column(Text)
    conduit_committee_zip = Column(Text)
    disbursement_dt = Column(Date)
    dissemination_date = Column(Date)
    election_type = Column(Text)
    election_type_full = Column(Text)
    expenditure_amount = Column(Numeric)
    expenditure_date = Column(Date)
    expenditure_description = Column(Text)
    file_number = Column(Integer)
    filer_first_name = Column(Text)
    filer_last_name = Column(Text)
    filer_middle_name = Column(Text)
    filer_prefix = Column(Text)
    filer_suffix = Column(Text)
    filing_date = Column(Date)
    filing_form = Column(Text)
    form_line_number = Column(Text)
    image_number = Column(Text)
    independent_sign_date = Column(Date)
    independent_sign_name = Column(Text)
    is_notice = Column(Boolean)
    line_number = Column(Text)
    line_number_label = Column(Text)
    link_id = Column(BigInteger)
    memo_code = Column(Text)
    memo_code_full = Column(Text)
    memo_text = Column(Text)
    memoed_subtotal = Column(Boolean)
    most_recent = Column(Boolean)
    notary_commission_expiration_date = Column(Date)
    notary_sign_date = Column(Date)
    notary_sign_name = Column(Text)
    office_total_ytd = Column(Numeric)
    original_sub_id = Column(Text)
    payee_city = Column(Text)
    payee_first_name = Column(Text)
    payee_last_name = Column(Text)
    payee_middle_name = Column(Text)
    payee_name = Column(Text)
    payee_prefix = Column(Text)
    payee_state = Column(Text)
    payee_street_1 = Column(Text)
    payee_street_2 = Column(Text)
    payee_suffix = Column(Text)
    payee_zip = Column(Text)
    pdf_url = Column(Text)
    previous_file_number = Column(Integer)
    report_type = Column(Text)
    report_year = Column(Text)
    schedule_type = Column(Text)
    schedule_type_full = Column(Text)
    semi_annual_bundled_refund = Column(Boolean)
    sub_id = Column(Text, primary_key=True)
    support_oppose_indicator = Column(Text)
    transaction_id = Column(Text)
    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_schedule_e_filing_date", ScheduleEExpenditure.filing_date)
Index("idx_schedule_e_expenditure_date", ScheduleEExpenditure.expenditure_date)
Index("idx_schedule_e_committee_id", ScheduleEExpenditure.committee_id)
Index("idx_schedule_e_candidate_id", ScheduleEExpenditure.candidate_id)
Index("idx_schedule_e_report_year", ScheduleEExpenditure.report_year)

class Totals(Base):
    __tablename__ = "totals"

    committee_id = Column(Text, primary_key=True)
    cycle = Column(Integer, primary_key=True)

    committee_name = Column(Text)
    committee_designation = Column(Text)
    committee_designation_full = Column(Text)
    committee_state = Column(Text)
    committee_type = Column(Text)
    committee_type_full = Column(Text)
    organization_type = Column(Text)
    organization_type_full = Column(Text)
    treasurer_name = Column(Text)
    filing_frequency = Column(Text)
    filing_frequency_full = Column(Text)
    party_full = Column(Text)
    coverage_start_date = Column(Date)
    coverage_end_date = Column(Date)
    transaction_coverage_date = Column(Date)
    first_f1_date = Column(Date)
    first_file_date = Column(Date)
    last_beginning_image_number = Column(Text)
    last_cash_on_hand_end_period = Column(Numeric)
    last_debts_owed_by_committee = Column(Numeric)
    last_debts_owed_to_committee = Column(Numeric)
    last_report_type_full = Column(Text)
    last_report_year = Column(Integer)
    all_other_loans = Column(Numeric)
    candidate_contribution = Column(Numeric)
    cash_on_hand_beginning_period = Column(Numeric)
    contribution_refunds = Column(Numeric)
    contributions = Column(Numeric)
    disbursements = Column(Numeric)
    individual_contributions = Column(Numeric)
    individual_itemized_contributions = Column(Numeric)
    individual_unitemized_contributions = Column(Numeric)
    loan_repayments = Column(Numeric)
    loan_repayments_candidate_loans = Column(Numeric)
    loan_repayments_other_loans = Column(Numeric)
    loans = Column(Numeric)
    loans_made_by_candidate = Column(Numeric)
    net_contributions = Column(Numeric)
    net_operating_expenditures = Column(Numeric)
    offsets_to_operating_expenditures = Column(Numeric)
    operating_expenditures = Column(Numeric)
    other_disbursements = Column(Numeric)
    other_political_committee_contributions = Column(Numeric)
    other_receipts = Column(Numeric)
    political_party_committee_contributions = Column(Numeric)
    receipts = Column(Numeric)
    refunded_individual_contributions = Column(Numeric)
    refunded_other_political_committee_contributions = Column(Numeric)
    refunded_political_party_committee_contributions = Column(Numeric)
    transfers_from_other_authorized_committee = Column(Numeric)
    transfers_to_other_authorized_committee = Column(Numeric)

    ingestion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    last_updated = Column(DateTime)


Index("idx_totals_committee_type", Totals.committee_type)
Index("idx_totals_committee_state", Totals.committee_state)
