CREATE TABLE committees (
    committee_id TEXT PRIMARY KEY,
    name TEXT,
    designation TEXT,
    designation_full TEXT,
    committee_type TEXT,
    committee_type_full TEXT,
    organization_type TEXT,
    organization_type_full TEXT,
    party TEXT,
    party_full TEXT,
    state TEXT,
    state_full TEXT,
    treasurer_name TEXT,
    street_1 TEXT,
    street_2 TEXT,
    city TEXT,
    zip TEXT,
    candidate_ids JSONB,
    cycles JSONB,
    cycles_has_activity JSONB,
    cycles_has_financial JSONB,
    first_f1_date DATE,
    first_file_date DATE,
    last_f1_date DATE,
    last_file_date DATE,
    filing_frequency TEXT,
    is_active BOOLEAN,
    jfc_committee JSONB,
    last_cycle_has_activity INTEGER,
    last_cycle_has_financial INTEGER,
    cycle INTEGER,
    party_type TEXT,
    party_type_full TEXT,
    sponsor_candidate_ids JSONB,
    sponsor_candidate_list JSONB,
    sponsor_candidate_name TEXT,
    sponsor_candidate_office TEXT,
    sponsor_candidate_office_district TEXT,
    sponsor_candidate_office_state TEXT,
    sponsor_candidate_party TEXT,
    sponsor_candidate_party_full TEXT,
    sponsor_candidate_state TEXT,
    sponsor_candidate_state_full TEXT,
    sponsor_candidate_type TEXT,
    sponsor_candidate_type_full TEXT,
    sponsor_candidate_zip TEXT,
    sponsor_committee_id TEXT,
    sponsor_committee_name TEXT,
    sponsor_committee_type TEXT,
    sponsor_committee_type_full TEXT,
    sponsor_committee_zip TEXT,
    sponsor_name TEXT,
    sponsor_state TEXT,
    sponsor_state_full TEXT,
    sponsor_type TEXT,
    sponsor_type_full TEXT,
    sponsor_zip TEXT,
    terminated BOOLEAN
);

CREATE INDEX idx_committees_name ON committees (name);
CREATE INDEX idx_committees_state ON committees (state);
CREATE INDEX idx_committees_party ON committees (party);
CREATE INDEX idx_committees_committee_type ON committees (committee_type);
CREATE INDEX idx_committees_cycles ON committees USING GIN (cycles);
CREATE INDEX idx_committees_candidate_ids ON committees USING GIN (candidate_ids);
CREATE INDEX idx_committees_is_active ON committees (is_active);
CREATE INDEX idx_committees_terminated ON committees (terminated);