CREATE TABLE pac_contributions (
    cmte_id TEXT,
    cmte_nm TEXT,
    cmte_tp CHAR(1),
    cmte_dsgn CHAR(1),
    cmte_pty_affiliation TEXT,
    cmte_city TEXT,
    cmte_st CHAR(2),
    cmte_zip TEXT,
    cand_id TEXT,
    cand_nm TEXT,
    cand_pty_affiliation TEXT,
    cand_election_yr INTEGER,
    transaction_pgi CHAR(5),
    transaction_tp CHAR(3),
    entity_tp CHAR(3),
    disb_dt TEXT,
    disb_amt NUMERIC,
    rpt_tp CHAR(3),
    file_num TEXT,
    memo_cd CHAR(1),
    memo_text TEXT,
    sub_id BIGINT,
    election_cycle INTEGER
);