CREATE TABLE schedule_e_expenditures (
    action_code TEXT,
    action_code_full TEXT,
    amendment_indicator TEXT,
    amendment_number INTEGER,
    amendment_indicator_desc TEXT,
    back_reference_schedule_name TEXT,
    back_reference_transaction_id TEXT,
    candidate TEXT,
    candidate_first_name TEXT,
    candidate_id TEXT,
    candidate_last_name TEXT,
    candidate_middle_name TEXT,
    candidate_name TEXT,
    candidate_office TEXT,
    candidate_office_district TEXT,
    candidate_office_full TEXT,
    candidate_office_state TEXT,
    candidate_office_state_full TEXT,
    candidate_party TEXT,
    candidate_prefix TEXT,
    candidate_suffix TEXT,

    -- Committee fields (flattened)
    affiliated_committee_name TEXT,
    candidate_ids JSONB,
    committee_city TEXT,
    committee_committee_id TEXT,
    committee_type TEXT,
    committee_type_full TEXT,
    committee_cycle INTEGER,
    committee_cycles JSONB,
    committee_cycles_has_activity JSONB,
    committee_cycles_has_financial JSONB,
    committee_designation TEXT,
    committee_designation_full TEXT,
    committee_filing_frequency TEXT,
    committee_first_f1_date DATE,
    committee_first_file_date DATE,
    committee_is_active BOOLEAN,
    committee_jfc_committee JSONB,
    committee_last_cycle_has_activity INTEGER,
    committee_last_cycle_has_financial INTEGER,
    committee_last_f1_date DATE,
    committee_last_file_date DATE,
    committee_name TEXT,
    committee_organization_type TEXT,
    committee_organization_type_full TEXT,
    committee_party TEXT,
    committee_party_full TEXT,
    committee_state TEXT,
    committee_state_full TEXT,
    committee_street_1 TEXT,
    committee_street_2 TEXT,
    committee_treasurer_name TEXT,
    committee_zip TEXT,

    committee_id TEXT,
    committee_name2 TEXT,
    conduit_committee_city TEXT,
    conduit_committee_id TEXT,
    conduit_committee_name TEXT,
    conduit_committee_state TEXT,
    conduit_committee_street1 TEXT,
    conduit_committee_street2 TEXT,
    conduit_committee_zip TEXT,
    disbursement_dt DATE,
    dissemination_date DATE,
    election_type TEXT,
    election_type_full TEXT,
    expenditure_amount NUMERIC,
    expenditure_date DATE,
    expenditure_description TEXT,
    file_number INTEGER,
    filer_first_name TEXT,
    filer_last_name TEXT,
    filer_middle_name TEXT,
    filer_prefix TEXT,
    filer_suffix TEXT,
    filing_date DATE,
    filing_form TEXT,
    form_line_number TEXT,
    image_number TEXT,
    independent_sign_date DATE,
    independent_sign_name TEXT,
    is_notice BOOLEAN,
    line_number TEXT,
    line_number_label TEXT,
    link_id BIGINT,
    memo_code TEXT,
    memo_code_full TEXT,
    memo_text TEXT,
    memoed_subtotal BOOLEAN,
    most_recent BOOLEAN,
    notary_commission_expiration_date DATE,
    notary_sign_date DATE,
    notary_sign_name TEXT,
    office_total_ytd NUMERIC,
    original_sub_id TEXT,
    payee_city TEXT,
    payee_first_name TEXT,
    payee_last_name TEXT,
    payee_middle_name TEXT,
    payee_name TEXT,
    payee_prefix TEXT,
    payee_state TEXT,
    payee_street_1 TEXT,
    payee_street_2 TEXT,
    payee_suffix TEXT,
    payee_zip TEXT,
    pdf_url TEXT,
    previous_file_number INTEGER,
    report_type TEXT,
    report_year INTEGER,
    schedule_type TEXT,
    schedule_type_full TEXT,
    semi_annual_bundled_refund BOOLEAN,
    sub_id TEXT PRIMARY KEY,
    support_oppose_indicator TEXT,
    transaction_id TEXT,
    ingestion_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP
);

CREATE INDEX idx_schedule_e_filing_date ON schedule_e_expenditures (filing_date);
CREATE INDEX idx_schedule_e_expenditure_date ON schedule_e_expenditures (expenditure_date);
CREATE INDEX idx_schedule_e_committee_id ON schedule_e_expenditures (committee_id);
CREATE INDEX idx_schedule_e_candidate_id ON schedule_e_expenditures (candidate_id);
CREATE INDEX idx_schedule_e_report_year ON schedule_e_expenditures (report_year);