CREATE TABLE schedule_a_contributions (
    amendment_indicator CHAR(1),
    amendment_indicator_desc TEXT,
    back_reference_schedule_name TEXT,
    back_reference_transaction_id TEXT,
    candidate_first_name TEXT,
    candidate_id VARCHAR(9),
    candidate_last_name TEXT,
    candidate_middle_name TEXT,
    candidate_name TEXT,
    candidate_office CHAR(1),
    candidate_office_district VARCHAR(2),
    candidate_office_full TEXT,
    candidate_office_state CHAR(2),
    candidate_office_state_full TEXT,
    candidate_prefix TEXT,
    candidate_suffix TEXT,
    committee_id VARCHAR(9),
    committee_name TEXT,
    conduit_committee_city TEXT,
    conduit_committee_id VARCHAR(9),
    conduit_committee_name TEXT,
    conduit_committee_state CHAR(2),
    conduit_committee_street1 TEXT,
    conduit_committee_street2 TEXT,
    conduit_committee_zip VARCHAR(10),
    contribution_receipt_amount NUMERIC(14,2),
    contribution_receipt_date DATE,
    contributor JSONB,
    contributor_aggregate_ytd NUMERIC(14,2),
    contributor_city TEXT,
    contributor_employer TEXT,
    contributor_first_name TEXT,
    contributor_id VARCHAR(9),
    contributor_last_name TEXT,
    contributor_middle_name TEXT,
    contributor_name TEXT,
    contributor_occupation TEXT,
    contributor_prefix TEXT,
    contributor_state CHAR(2),
    contributor_street_1 TEXT,
    contributor_street_2 TEXT,
    contributor_suffix TEXT,
    contributor_zip VARCHAR(10),
    donor_committee_name TEXT,
    election_type VARCHAR(5),
    election_type_full TEXT,
    entity_type CHAR(3),
    entity_type_desc TEXT,
    fec_election_type_desc TEXT,
    fec_election_year INT,
    file_number INT,
    filing_form VARCHAR(8),
    image_number BIGINT,
    increased_limit BOOLEAN,
    is_individual BOOLEAN,
    line_number VARCHAR(8),
    line_number_label TEXT,
    link_id BIGINT,
    load_date TIMESTAMP,
    memo_code CHAR(1),
    memo_code_full TEXT,
    memo_text TEXT,
    memoed_subtotal BOOLEAN,
    national_committee_nonfederal_account TEXT,
    original_sub_id BIGINT,
    pdf_url TEXT,
    receipt_type VARCHAR(3),
    receipt_type_desc TEXT,
    receipt_type_full TEXT,
    recipient_committee_designation CHAR(3),
    recipient_committee_org_type CHAR(3),
    recipient_committee_type CHAR(3),
    report_type VARCHAR(8),
    report_year INT,
    schedule_type VARCHAR(8),
    schedule_type_full TEXT,
    sub_id BIGINT PRIMARY KEY,
    transaction_id VARCHAR(32),
    two_year_transaction_period INT,
    unused_contbr_id VARCHAR(9),
    ingestion_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP
);

-- Index to speed up queries filtered by committee_id
CREATE INDEX idx_schedule_a_committee_id
ON schedule_a_contributions (committee_id);

-- Index for filtering by election cycle period
CREATE INDEX idx_schedule_a_two_year_period
ON schedule_a_contributions (two_year_transaction_period);

-- Index for filtering/sorting by contribution amount
CREATE INDEX idx_schedule_a_amount
ON schedule_a_contributions (contribution_receipt_amount);

-- Index for date-based filtering or sorting
CREATE INDEX idx_schedule_a_date
ON schedule_a_contributions (contribution_receipt_date);