CREATE TABLE schedule_b_disbursements (
    amendment_indicator TEXT,
    amendment_indicator_desc TEXT,
    back_reference_schedule_name TEXT,
    back_reference_transaction_id TEXT,
    beneficiary_committee_name TEXT,
    candidate_first_name TEXT,
    candidate_id TEXT,
    candidate_last_name TEXT,
    candidate_middle_name TEXT,
    candidate_name TEXT,
    candidate_office TEXT,
    candidate_office_district TEXT,
    candidate_office_full TEXT,
    candidate_office_state TEXT,
    candidate_office_state_full TEXT,
    candidate_party TEXT,
    candidate_prefix TEXT,
    candidate_suffix TEXT,
    committee_id TEXT,
    committee_name TEXT,
    conduit_committee_city TEXT,
    conduit_committee_id TEXT,
    conduit_committee_name TEXT,
    conduit_committee_state TEXT,
    conduit_committee_street1 TEXT,
    conduit_committee_street2 TEXT,
    conduit_committee_zip TEXT,
    disbursement_amount NUMERIC,
    disbursement_date DATE,
    disbursement_description TEXT,
    disbursement_type TEXT,
    disbursement_type_full TEXT,
    entity_type TEXT,
    entity_type_desc TEXT,
    fec_election_type_desc TEXT,
    fec_election_year INTEGER,
    file_number INTEGER,
    filing_form TEXT,
    image_number TEXT,
    is_electioneering_communication BOOLEAN,
    is_independent_expenditure BOOLEAN,
    is_party_expenditure BOOLEAN,
    line_number TEXT,
    line_number_label TEXT,
    link_id BIGINT,
    load_date DATE,
    memo_code TEXT,
    memo_code_full TEXT,
    memo_text TEXT,
    memoed_subtotal BOOLEAN,
    national_committee_nonfederal_account TEXT,
    original_sub_id TEXT,
    pdf_url TEXT,
    recipient_city TEXT,
    recipient_committee_designation TEXT,
    recipient_committee_designation_full TEXT,
    recipient_committee_id TEXT,
    recipient_committee_name TEXT,
    recipient_committee_org_type TEXT,
    recipient_committee_org_type_full TEXT,
    recipient_committee_type TEXT,
    recipient_committee_type_full TEXT,
    recipient_name TEXT,
    recipient_state TEXT,
    recipient_street_1 TEXT,
    recipient_street_2 TEXT,
    recipient_zip TEXT,
    ref_disp_excess_amt NUMERIC,
    ref_disp_excess_amt_desc TEXT,
    ref_disp_excess_flg TEXT,
    ref_disp_excess_flg_desc TEXT,
    report_type TEXT,
    report_year INTEGER,
    schedule_type TEXT,
    schedule_type_full TEXT,
    semi_annual_bundled_refund BOOLEAN,
    sub_id TEXT PRIMARY KEY,
    transaction_id TEXT,
    two_year_transaction_period INTEGER,
    unused_recipient_id TEXT
);

-- Recommended indexes for efficient querying
CREATE INDEX idx_sched_b_disb_date ON schedule_b_disbursements (disbursement_date);
CREATE INDEX idx_sched_b_committee_id ON schedule_b_disbursements (committee_id);
CREATE INDEX idx_sched_b_candidate_id ON schedule_b_disbursements (candidate_id);
CREATE INDEX idx_sched_b_report_year ON schedule_b_disbursements (report_year);
CREATE INDEX idx_sched_b_recipient_name ON schedule_b_disbursements (recipient_name);
CREATE INDEX idx_sched_b_transaction_id ON schedule_b_disbursements (transaction_id);