CREATE TABLE totals (
    committee_id TEXT,
    cycle INTEGER,
    committee_name TEXT,
    committee_designation TEXT,
    committee_designation_full TEXT,
    committee_state TEXT,
    committee_type TEXT,
    committee_type_full TEXT,
    organization_type TEXT,
    organization_type_full TEXT,
    treasurer_name TEXT,
    filing_frequency TEXT,
    filing_frequency_full TEXT,
    party_full TEXT,
    coverage_start_date DATE,
    coverage_end_date DATE,
    transaction_coverage_date DATE,
    first_f1_date DATE,
    first_file_date DATE,
    last_beginning_image_number TEXT,
    last_cash_on_hand_end_period NUMERIC,
    last_debts_owed_by_committee NUMERIC,
    last_debts_owed_to_committee NUMERIC,
    last_report_type_full TEXT,
    last_report_year INTEGER,
    all_other_loans NUMERIC,
    candidate_contribution NUMERIC,
    cash_on_hand_beginning_period NUMERIC,
    contribution_refunds NUMERIC,
    contributions NUMERIC,
    disbursements NUMERIC,
    individual_contributions NUMERIC,
    individual_itemized_contributions NUMERIC,
    individual_unitemized_contributions NUMERIC,
    loan_repayments NUMERIC,
    loan_repayments_candidate_loans NUMERIC,
    loan_repayments_other_loans NUMERIC,
    loans NUMERIC,
    loans_made_by_candidate NUMERIC,
    net_contributions NUMERIC,
    net_operating_expenditures NUMERIC,
    offsets_to_operating_expenditures NUMERIC,
    operating_expenditures NUMERIC,
    other_disbursements NUMERIC,
    other_political_committee_contributions NUMERIC,
    other_receipts NUMERIC,
    political_party_committee_contributions NUMERIC,
    receipts NUMERIC,
    refunded_individual_contributions NUMERIC,
    refunded_other_political_committee_contributions NUMERIC,
    refunded_political_party_committee_contributions NUMERIC,
    transfers_from_other_authorized_committee NUMERIC,
    transfers_to_other_authorized_committee NUMERIC,
    ingestion_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP,
    PRIMARY KEY (committee_id, cycle)
);

-- Composite index on (committee_id, cycle) is automatically created as the primary key,
-- but you can add additional indexes as needed:
CREATE INDEX idx_totals_committee_type ON totals (committee_type);
CREATE INDEX idx_totals_committee_state ON totals (committee_state);